target ‘SwiftDemo’ do
use_frameworks!

# 主模块(必须) 3.3.2
#pod 'ShareSDK3', '~>3.6.1'
# Mob 公共库(必须) 如果同时集成SMSSDK iOS2.0:可看此注意事项：http://bbs.mob.com/thread-20051-1-1.html
#pod 'MOBFoundation'

# UI模块(非必须，需要用到ShareSDK提供的分享菜单栏和分享编辑页面需要以下1行)
#pod 'ShareSDK3/ShareSDKUI'

# 平台SDK模块(对照一下平台，需要的加上。如果只需要QQ、微信、新浪微博，只需要以下3行)
#pod 'ShareSDK3/ShareSDKPlatforms/QQ'
#pod 'ShareSDK3/ShareSDKPlatforms/SinaWeibo'
#pod 'ShareSDK3/ShareSDKPlatforms/WeChat'


## 高德地图
##, '~> 3.3.0'
#pod 'AMap2DMap'
##, '~> 3.3.0'
#pod 'AMapSearch'
##, '~> 1.2.2'
#pod 'AMapLocation'

#百度地图SDK
#pod 'BaiduMapKit', '~>3.4.2'
#pod 'AMap2DMap-NO-IDFA', '~>4.6.0'
#pod 'AMapSearch-NO-IDFA', '~>4.5.0'
#pod 'AMapLocation-NO-IDFA', '~>2.3.0'

#1.5.6 (一个自定义tabbar三方控件)
#pod 'CYLTabBarController', '~>1.10.0'

# 分享一般使用ShareSDK, 地图一般使用高德地图

#pod 'MJRefresh'#, '~>3.1.12'

pod 'UMengAnalytics-NO-IDFA'

pod 'MJExtension', '~>3.0.13'

pod 'pop', '~> 1.0'

#pod 'AliyunOSSiOS', '~> 2.6.0'

pod 'JPush'#, '~> 3.0.7'

pod 'HyphenateLite'

#pod 'EaseUI', :git => 'https://github.com/easemob/easeui-ios-hyphenate-cocoapods.git'

# 键盘遮挡的三方
pod 'IQKeyboardManager', '~>5.0.0'
pod 'SVProgressHUD', '~>2.1.2'

pod 'Masonry'

# 轮播图
#pod 'SDCycleScrollView', '~>1.65'

platform :ios, '8.0'
pod 'SDWebImage', '~>3.8.1'

#source 'https://github.com/CocoaPods/Specs.git'

#platform :ios, '8.0'
pod 'AFNetworking', '~> 3.0'

pod 'DZNEmptyDataSet'

pod 'FDFullscreenPopGesture', '1.1'

#pod 'PPNetworkHelper',:git => 'https://github.com/jkpang/PPNetworkHelper.git'

pod 'GPUImage'



#pod 'lottie-ios', :git => 'https://github.com/airbnb/lottie-ios.git'


end